# netlify.toml
[build]
  publish = "build" # 对应你之前配置的 Vite 打包输出目录（如果是 dist 就改成 dist）

[[redirects]]
  from = "/*" # 匹配所有路径
  to = "/index.html" # 都重定向到 index.html
  status = 200 # 状态码 200（不是 301 跳转，而是静默重写）